version: "3"
services:
  front_react:
    build: ./FrontEnd
    ports:
      - 10103:3000
    depends_on:
      - back_springboot
  back_springboot:
    build: ./BackEnd
    restart: always
    ports:
      - 10102:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db_mysql:3306/library?autoReconnect=true&useSSL=false
    depends_on:
      - db_mysql
  db_mysql:
    image: "mysql:8.0"
    restart: always
    ports:
      - 10101:3306
    environment:
      MYSQL_DATABASE: library
      MYSQL_USER: us3rt3st
      MYSQL_PASSWORD: P@ssw0rd
      MYSQL_ROOT_PASSWORD: P@ssw0rd
