version: "3"

volumes:
  mysql_data:

networks:
  backend_net:

services:
  front_react:
    build: ./FrontEnd
    container_name: frontend
    networks:
      - backend_net
    ports:
      - 10101:3000
    depends_on:
      - back_springboot
  back_springboot:
    build: ./BackEnd
    container_name: backend
    restart: on-failure
    networks:
      - backend_net
    ports:
      - 10102:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://database/library?autoReconnect=true&allowPublicKeyRetrieval=true&useSSL=false
    depends_on:
      - db_mysql
  db_mysql:
    image: "mysql:8.0"
    container_name: database
    networks:
      - backend_net
    ports:
      - 10103:3306
    environment:
      MYSQL_DATABASE: library
      MYSQL_USER: us3rt3st
      MYSQL_PASSWORD: P@ssw0rd
      MYSQL_ROOT_PASSWORD: P@ssw0rd
    volumes:
      - mysql_data:/var/lib/mysql
